# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwd/Protobuf/Progression/progression.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dwd/Protobuf/Progression/progression.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dwd.Protobuf import base_pb2 as dwd_dot_Protobuf_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*dwd/Protobuf/Progression/progression.proto\x12\x18\x64wd.Protobuf.Progression\x1a\x17\x64wd/Protobuf/base.proto\"\xc0\x01\n\x08Scenario\x12&\n\nscenarioID\x18\x01 \x01(\x0b\x32\x12.dwd.Protobuf.UUID\x12+\n\nattributes\x18\x02 \x03(\x0b\x32\x17.dwd.Protobuf.Attribute\x12$\n\x08\x63hildren\x18\x03 \x03(\x0b\x32\x12.dwd.Protobuf.UUID\x12\x19\n\x11\x65ntryRequirements\x18\x04 \x01(\t\x12\x1e\n\x16\x63ompletionRequirements\x18\x05 \x01(\t\"\xe8\x01\n\x0c\x41llScenarios\x12\x35\n\tcompleted\x18\x01 \x03(\x0b\x32\".dwd.Protobuf.Progression.Scenario\x12\x35\n\tavailable\x18\x02 \x03(\x0b\x32\".dwd.Protobuf.Progression.Scenario\x12\x37\n\x0bunavailable\x18\x03 \x03(\x0b\x32\".dwd.Protobuf.Progression.Scenario\x12\x31\n\x05roots\x18\x04 \x03(\x0b\x32\".dwd.Protobuf.Progression.Scenariob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwd.Protobuf.Progression.progression_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENARIO']._serialized_start=98
  _globals['_SCENARIO']._serialized_end=290
  _globals['_ALLSCENARIOS']._serialized_start=293
  _globals['_ALLSCENARIOS']._serialized_end=525
# @@protoc_insertion_point(module_scope)
