import unittest

from spirit.game.starter_content import (
    SET_CODE_MAP,
    STARTER_DECKS,
    parse_tcgo_decklist,
)


ALAKAZAM_EXPORT = """
****** Pokémon Trading Card Game Deck List ******

##Pokémon - 22

* 3 Dunsparce JTG 120
* 3 Dudunsparce TEF 129
* 1 Fezandipiti ex ASC 142
* 1 Shaymin DRI 10
* 1 Genesect SFA 40
* 4 Abra MEG 54
* 1 Dedenne SSP 87
* 1 Elgyem BLK 40
* 4 Kadabra MEG 55
* 3 Alakazam MEG 56

##Trainer Cards - 32

* 4 Dawn PFL 87
* 3 Hilda WHT 84
* 2 Boss's Orders MEG 114
* 1 Lana's Aid TWM 155
* 4 Buddy-Buddy Poffin TEF 144
* 4 Poké Pad POR 81
* 3 Rare Candy MEG 125
* 2 Enhanced Hammer TWM 148
* 1 Sacred Ash DRI 168
* 1 Night Stretcher ASC 196
* 1 Lucky Helmet TWM 158
* 1 Handheld Fan TWM 150
* 1 Air Balloon ASC 181
* 4 Nighttime Mine ASC 197

##Energy - 6

* 4 Telepathic Psychic Energy POR 88
* 1 Psychic Energy Energy 5
* 1 Enriching Energy SSP 191

Total Cards - 60

****** Deck List Generated by the Pokémon TCG Online www.pokemon.com/TCGO ******
"""


class ParseTcgoDecklistTests(unittest.TestCase):
    def test_parses_ptcgo_export_and_ignores_headers(self):
        entries = parse_tcgo_decklist(ALAKAZAM_EXPORT)
        self.assertEqual(sum(count for count, _, _ in entries), 60)
        self.assertEqual(entries[0], (3, "JTG", 120))
        self.assertEqual(entries[-2], (1, "Energy", 5))
        self.assertEqual(entries[-1], (1, "SSP", 191))

    def test_parses_limitless_lines_without_asterisks(self):
        entries = parse_tcgo_decklist("3 Dunsparce JTG 120\n4 Ultra Ball BRS 186\n")
        self.assertEqual(entries, [(3, "JTG", 120), (4, "BRS", 186)])

    def test_set_code_map_covers_export_codes(self):
        self.assertEqual(SET_CODE_MAP["JTG"], "SV09")
        self.assertEqual(SET_CODE_MAP["MEG"], "ME1")
        self.assertEqual(SET_CODE_MAP["ENERGY"], "Free_Energy")
        self.assertEqual(SET_CODE_MAP["SSH"], "SWSH1")
        self.assertEqual(SET_CODE_MAP["FREE_ENERGY"], "Free_Energy")

    def test_starter_decks_parse_to_sixty_cards(self):
        for name, decklist in STARTER_DECKS:
            entries = parse_tcgo_decklist(decklist)
            self.assertEqual(
                sum(count for count, _, _ in entries),
                60,
                f"{name} is not 60 cards",
            )


if __name__ == "__main__":
    unittest.main()
