# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dwd/Protobuf/base.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dwd/Protobuf/base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64wd/Protobuf/base.proto\x12\x0c\x64wd.Protobuf\"\x1e\n\x04UUID\x12\n\n\x02lo\x18\x01 \x01(\x06\x12\n\n\x02hi\x18\x02 \x01(\x06\"A\n\rKeyObjectPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.dwd.Protobuf.Object\"\xf4\x02\n\x06Object\x12-\n\nobjectType\x18\x01 \x01(\x0e\x32\x19.dwd.Protobuf.Object.Type\x12(\n\narrayValue\x18\x02 \x03(\x0b\x32\x14.dwd.Protobuf.Object\x12\x34\n\x0f\x64ictionaryValue\x18\x03 \x03(\x0b\x32\x1b.dwd.Protobuf.KeyObjectPair\x12\x13\n\x0bstringValue\x18\x04 \x01(\t\x12\x11\n\tboolValue\x18\x05 \x01(\x08\x12\x10\n\x08intValue\x18\x06 \x01(\x05\x12\x12\n\nfloatValue\x18\x07 \x01(\x02\x12%\n\tguidValue\x18\x08 \x01(\x0b\x32\x12.dwd.Protobuf.UUID\"f\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x41RRAY\x10\x01\x12\x08\n\x04\x44ICT\x10\x02\x12\n\n\x06STRING\x10\x03\x12\x08\n\x04\x42OOL\x10\x04\x12\x07\n\x03INT\x10\x05\x12\t\n\x05\x46LOAT\x10\x06\x12\x08\n\x04UUID\x10\x07\x12\x08\n\x04JSON\x10\x08\"\x93\x01\n\tAttribute\x12\x0c\n\x04name\x18\x01 \x01(\x11\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.dwd.Protobuf.Object\x12+\n\roriginalValue\x18\x03 \x01(\x0b\x32\x14.dwd.Protobuf.Object\x12&\n\x08modValue\x18\x04 \x01(\x0b\x32\x14.dwd.Protobuf.Object\"Z\n\tArchetype\x12 \n\x04guid\x18\x01 \x01(\x0b\x32\x12.dwd.Protobuf.UUID\x12+\n\nattributes\x18\x02 \x03(\x0b\x32\x17.dwd.Protobuf.Attributeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwd.Protobuf.base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UUID']._serialized_start=41
  _globals['_UUID']._serialized_end=71
  _globals['_KEYOBJECTPAIR']._serialized_start=73
  _globals['_KEYOBJECTPAIR']._serialized_end=138
  _globals['_OBJECT']._serialized_start=141
  _globals['_OBJECT']._serialized_end=513
  _globals['_OBJECT_TYPE']._serialized_start=411
  _globals['_OBJECT_TYPE']._serialized_end=513
  _globals['_ATTRIBUTE']._serialized_start=516
  _globals['_ATTRIBUTE']._serialized_end=663
  _globals['_ARCHETYPE']._serialized_start=665
  _globals['_ARCHETYPE']._serialized_end=755
# @@protoc_insertion_point(module_scope)
